return {
  file = {
    file = "",
    modified = "",
    readonly = "",
    new = "",
  },

  indent = {
    marker = "│",
    last = "└",
  },
  folder = {
    closed = "",
    open = "",
    empty = "ﰊ",
    collapsed = "",
    expanded = "",
  },
  git = {
    signs = {
      add = "│",
      topdelete = "󱨉",
      delete = "│",
      changedelete = "│",
      change = "│",
      untracked = "│",
    },
    git = "",
    add = "",
    branch = "",
    change = "",
    conflict = "",
    delete = "",
    ignored = "◌",
    renamed = "",
    staged = "✓",
    unstaged = "✗",
    untracked = "★",
  },
  diagnostics = {
    error = " ",
    warn = " ",
    hint = " ",
    info = " ",
  },
  kinds = {
    Array = " ",
    Boolean = " ",
    Class = "",
    Color = " ",
    Constant = " ",
    Constructor = "",
    Enum = "",
    EnumMember = "",
    Event = "",
    Field = " ",
    File = "",
    Folder = "",
    Function = "",
    Interface = "",
    Key = "",
    Keyword = "",
    Method = "m",
    Module = "",
    Namespace = " ",
    Null = "ﳠ ",
    Operator = "",
    Package = " ",
    Property = "",
    Reference = "",
    Snippet = "",
    Struct = "",
    Text = "",
    TypeParameter = " ",
    Unit = "",
    Value = "",
    Variable = "",
  },
}
